os:
    - Visual Studio 2015

platform:
    - x86
    - x64

configuration:
    - Debug
    - Release

install:
    - cmd: git submodule update --init --recursive
    - cmd: MakeSolution.bat

build:
    parallel: true
    project: build\CpuTrace.sln
